sudo: required
services:
  - docker

before_install:
  - docker build -t lesha/react-test  -f ./client/dev.Dockerfile ./client
   
script: 
  - docker run lesha/react-test npm run test -- --coverage

after_success:
  - docker build -t lesha/multi-client ./client
  - docker build -t lesha/multi-nginx ./nginx
  - docker build -t lesha/multi-server ./server
  - docker build -t lesha/multi-worker ./worker

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin 
# Push image to docker hub
  - docker push lesha/multi-client
  - docker push lesha/multi-nginx
  - docker push lesha/multi-server
  - docker push lesha/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-185672218489" 
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"