version: '3'

services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  api:
    build:
      dockerfile:  dev.Dockerfile
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client: 
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379

  worker: 
    build:
      dockerfile: dev.Dockerfile
      context: ./worker
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    build:
      dockerfile: dev.Dockerfile
      context: ./nginx
    restart: always
    ports: 
      - '3050:80'



